format:
  version: 1

root:
  class: matrix
  cols: 3
  rows: 2
  children:
    - data_name_1
    - data_name_2
    - data_name_3
    - data_name_4

data_name_1:
  class: titled
  title: Speed (km/h)
  topic:
    name: /test
    type: std_msgs/msg/Header
    data: stamp.sec

data_name_2:
  class: titled
  title: Angle (rad)

data_name_3:
  class: titled
  title: Angle (deg)

data_name_4:
  class: titled
  title: Accel (m/s^2)
