# --------------------------------------------------
# headers
# --------------------------------------------------
version: alpha 1
root: main

# --------------------------------------------------
# monitors
# --------------------------------------------------
monitors:

  main:
    class: matrix
    cols: 3
    rows: 2
    children:
      - data_name_1
      - data_name_2
      - data_name_3
      - data_name_4

  data_name_1:
    class: titled
    title: Second
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: stamp.sec, type: auto}

  data_name_2:
    class: titled
    title: Nanosecond
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: stamp.nanosec, type: auto}

  data_name_3:
    class: titled
    title: Frame
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: frame_id, type: auto}

  data_name_4:
    class: titled
    title: Accel (m/s^2)
    topic: {name: /monitor/data, type: std_msgs/msg/Float32}
    field: {name: data, type: auto}
