# --------------------------------------------------
# headers
# --------------------------------------------------
version: alpha 1
root: main

# --------------------------------------------------
# monitors
# --------------------------------------------------
monitors:

  main:
    class: matrix
    cols: 3
    rows: 2
    children:
      - data_name_1
      - data_name_2
      - data_name_3
      - data_name_4
      - data_name_5

  data_name_1:
    class: titled
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: stamp.sec, type: auto}
    title: Second

  data_name_2:
    class: titled
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: stamp.nanosec, type: auto}
    title: Nanosecond

  data_name_3:
    class: titled
    topic: {name: /monitor/float, type: std_msgs/msg/Float32}
    field: {name: data, type: auto}
    title: Float Value

  data_name_4:
    class: simple
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: frame_id, type: auto}
    title: Frame

  data_name_5:
    class: simple
    topic: {name: /monitor/int, type: std_msgs/msg/Int32}
    field: {name: data, type: auto}
    title: Value
    rules:
      - func: switch
        args:
          1: {value: A, style: {back-color: "#FF00FF"}}
          2: {value: B, style: {back-color: "#00FF00"}}
          3: {value: C, style: {back-color: "#00FFFF"}}
